### ISSUE TITLE
adding Content-Security-Policy header

### ISSUE THREAD

**Issue by carloslfu** [ozzyonfire/shopify-next-app#6]
I noticed in the previous template this was implemented, but it needs to be added here. A way to implement it is using middleware, like here: https://github.com/kinngh/shopify-nextjs-prisma-app/commit/a7bb21a38d398c2e2b9c7c295ea729865ad59069. What do you think?

**Comment by ozzyonfire** [comment]
good point. I remember removing that but forgot to figure out where it should go. I will see if I can add it to some middleware, or you can open a pull-request and try to add it in

**Comment by ozzyonfire** [comment]
should be fixed with the latest commit.

**Comment by carloslfu** [comment]
Awesome! Thanks!
